version: "3.8"

services:
  symfony:
    build:
      context: ./symfony
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./symfony:/var/www/symfony

  vue:
    build:
      context: ./vue
    ports:
      - "8080:8080"
    depends_on:
      - symfony
    volumes:
      - ./vue:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: nom_de_la_base
      MYSQL_USER: username
      MYSQL_PASSWORD: your_mysql_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
