hello_world:
    path: /hello
    controller: App\Controller\HelloWorldController::hello
    methods: [GET]
utilisateur_index:
    path: /utilisateurs
    controller: App\Controller\UtilisateurController::index
    methods: GET

utilisateur_create:
    path: /utilisateur
    controller: App\Controller\UtilisateurController::create
    methods: POST

utilisateur_show:
    path: /utilisateur/{id}
    controller: App\Controller\UtilisateurController::show
    methods: GET

utilisateur_update:
    path: /utilisateur/{id}
    controller: App\Controller\UtilisateurController::update
    methods: PUT

utilisateur_delete:
    path: /utilisateur/{id}
    controller: App\Controller\UtilisateurController::delete
    methods: DELETE

# Routes for EquipeController
equipe_index:
    path: /equipes
    controller: App\Controller\EquipeController::index
    methods: GET

equipe_create:
    path: /equipe
    controller: App\Controller\EquipeController::create
    methods: POST

equipe_show:
    path: /equipe/{id}
    controller: App\Controller\EquipeController::show
    methods: GET

equipe_update:
    path: /equipe/{id}
    controller: App\Controller\EquipeController::update
    methods: PUT

equipe_delete:
    path: /equipe/{id}
    controller: App\Controller\EquipeController::delete
    methods: DELETE
# Routes for CandidatureController
candidature_index:
    path: /candidatures
    controller: App\Controller\CandidatureController::index
    methods: GET

candidature_create:
    path: /candidature
    controller: App\Controller\CandidatureController::create
    methods: POST

candidature_show:
    path: /candidature/{id}
    controller: App\Controller\CandidatureController::show
    methods: GET

candidature_update:
    path: /candidature/{id}
    controller: App\Controller\CandidatureController::update
    methods: PUT

candidature_delete:
    path: /candidature/{id}
    controller: App\Controller\CandidatureController::delete
    methods: DELETE
# Routes for RHController
rh_index:
    path: /rhs
    controller: App\Controller\RHController::index
    methods: GET

rh_create:
    path: /rh
    controller: App\Controller\RHController::create
    methods: POST

rh_show:
    path: /rh/{id}
    controller: App\Controller\RHController::show
    methods: GET

rh_update:
    path: /rh/{id}
    controller: App\Controller\RHController::update
    methods: PUT

rh_delete:
    path: /rh/{id}
    controller: App\Controller\RHController::delete
    methods: DELETE
# Routes for OffreEmploiController
offre_emploi_index:
    path: /offres
    controller: App\Controller\OffreEmploiController::index
    methods: GET

offre_emploi_create:
    path: /offre
    controller: App\Controller\OffreEmploiController::create
    methods: POST

offre_emploi_show:
    path: /offre/{id}
    controller: App\Controller\OffreEmploiController::show
    methods: GET

offre_emploi_update:
    path: /offre/{id}
    controller: App\Controller\OffreEmploiController::update
    methods: PUT

offre_emploi_delete:
    path: /offre/{id}
    controller: App\Controller\OffreEmploiController::delete
    methods: DELETE
# Routes for NotificationController
notification_index:
    path: /notifications
    controller: App\Controller\NotificationController::index
    methods: GET

notification_create:
    path: /notification
    controller: App\Controller\NotificationController::create
    methods: POST

notification_show:
    path: /notification/{id}
    controller: App\Controller\NotificationController::show
    methods: GET

notification_update:
    path: /notification/{id}
    controller: App\Controller\NotificationController::update
    methods: PUT

notification_delete:
    path: /notification/{id}
    controller: App\Controller\NotificationController::delete
    methods: DELETE
# Routes for CoopteurController
coopteur_index:
    path: /coopteurs
    controller: App\Controller\CoopteurController::index
    methods: GET

coopteur_create:
    path: /coopteur
    controller: App\Controller\CoopteurController::create
    methods: POST

coopteur_show:
    path: /coopteur/{id}
    controller: App\Controller\CoopteurController::show
    methods: GET

coopteur_update:
    path: /coopteur/{id}
    controller: App\Controller\CoopteurController::update
    methods: PUT

coopteur_delete:
    path: /coopteur/{id}
    controller: App\Controller\CoopteurController::delete
    methods: DELETE
# Routes for ClassementController
classement_index:
    path: /classements
    controller: App\Controller\ClassementController::index
    methods: GET

classement_create:
    path: /classement
    controller: App\Controller\ClassementController::create
    methods: POST

classement_show:
    path: /classement/{id}
    controller: App\Controller\ClassementController::show
    methods: GET

classement_update:
    path: /classement/{id}
    controller: App\Controller\ClassementController::update
    methods: PUT

classement_delete:
    path: /classement/{id}
    controller: App\Controller\ClassementController::delete
    methods: DELETE
# Routes for CooptationOffreEmploiController
cooptation_offre_emploi_index:
    path: /cooptation-offres
    controller: App\Controller\CooptationOffreEmploiController::index
    methods: GET

cooptation_offre_emploi_create:
    path: /cooptation-offre
    controller: App\Controller\CooptationOffreEmploiController::create
    methods: POST

cooptation_offre_emploi_show:
    path: /cooptation-offre/{id}
    controller: App\Controller\CooptationOffreEmploiController::show
    methods: GET

cooptation_offre_emploi_update:
    path: /cooptation-offre/{id}
    controller: App\Controller\CooptationOffreEmploiController::update
    methods: PUT

cooptation_offre_emploi_delete:
    path: /cooptation-offre/{id}
    controller: App\Controller\CooptationOffreEmploiController::delete
    methods: DELETE
# Routes for CooptationController
cooptation_index:
    path: /cooptations
    controller: App\Controller\CooptationController::index
    methods: GET

cooptation_create:
    path: /cooptation
    controller: App\Controller\CooptationController::create
    methods: POST

cooptation_show:
    path: /cooptation/{id}
    controller: App\Controller\CooptationController::show
    methods: GET

cooptation_update:
    path: /cooptation/{id}
    controller: App\Controller\CooptationController::update
    methods: PUT

cooptation_delete:
    path: /cooptation/{id}
    controller: App\Controller\CooptationController::delete
    methods: DELETE
# Routes for EquipeUtilisateurController
equipe_utilisateur_index:
    path: /equipe-utilisateurs
    controller: App\Controller\EquipeUtilisateurController::index
    methods: GET

equipe_utilisateur_create:
    path: /equipe-utilisateur
    controller: App\Controller\EquipeUtilisateurController::create
    methods: POST

equipe_utilisateur_show:
    path: /equipe-utilisateur/{id}
    controller: App\Controller\EquipeUtilisateurController::show
    methods: GET

equipe_utilisateur_update:
    path: /equipe-utilisateur/{id}
    controller: App\Controller\EquipeUtilisateurController::update
    methods: PUT

equipe_utilisateur_delete:
    path: /equipe-utilisateur/{id}
    controller: App\Controller\EquipeUtilisateurController::delete
    methods: DELETE
